
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qd_admin
    username: root
    password: aA@123456
    hikari:
        minimum-idle: 10
        maximum-pool-size: 20
        # 客户端最大等待时间
        connection-timeout: 60000
  redis:
    database: 15
    host: localhost
    port: 6379
    password:

logging:
  level:
    # 日志级别 debug>info>warn>error
    com.lhd.qd: debug

qd:
  log:
    http: true
  security:
    salt-times: 128
  token:
    expires-minutes: 600
  user:
    init-pwd: 123456
    ignore-url: /,/login,/logout,/dict/page/cache,/csrf,/swagger-ui.html,/v2/api-docs,/swagger-resources/**,/webjars/springfox-swagger-ui/**
